#!/bin/bash

pre_install(){
	if [ ! -f "~/.vcash/"]; then
		echo "Creating new folders..."
		mkdir -p ~/.vcash/src/
		mkdir -p ~/.vcash/data/
		mkdir -p ~/.vcash/backup/
	fi
}

pre_upgrade(){
	if [ -f "~/.vcash/src/"]; then
		echo "Deleting old src files..."
		rm -rf ~/.vcash/src/ 
		mkdir -p ~/.vcash/src/
	fi
}

pre_remove(){
	echo "Backing up your folders from ~/.vcash/ to Downloads/vcash-removal-backup/"
	cp -r -i ~/.vcash/data ~/.vcash/backup Downloads/vcash-removal-backup/
}
